# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1aaf2efe9162b61e0a87b4052174f0482537e86f401defd8e8d36fb6ec44831ff27071c0a4ae3f2392485ea0a29e604dae6edf2cd2928ab62c5b153a4b4433c0

test:
  secret_key_base: c5d4426943ae8f8ec3b5611dfc2dd4c17fc1da8088c9e8f6cdbd31de1df627ee72dc44ce750c2058f6187b4e4930cddea9ff867e2c5526f96c3d6ae7956e0b1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
